config/routes.rb
Coursebeat::Application.routes.draw do

  resources :lessons, except: [:new, :create]
  resources :instructors, except: [:index]
  resources :sessions, only: [:new, :create]
  resources :courses do
  	resources :lessons, only: [:new, :create]
  end

  # get '/lessons/:secret_code', to: "lessons#show", as: "lesson_code"
  get '/courses/:secret_code', to: "courses#show", as: "course_code"
  # get '/instructors/:instructor_secret_code', to: "instructors#show", as: "instructor_code" 

  root to: "lessons#index"

  post "/lessons/:id/update", to: "lessons#update"

  post "/courses/:id/remove", to: "courses#remove_instructor", as: "remove_instructor"

  get '/logout' => "sessions#destroy"

  match '*path' => redirect('/')

# $ rake routes
#        root        /                             lessons#index
#             POST   /lessons/:id/update(.:format) lessons#update
#     lessons GET    /lessons(.:format)            lessons#index
#             POST   /lessons(.:format)            lessons#create
#  new_lesson GET    /lessons/new(.:format)        lessons#new
# edit_lesson GET    /lessons/:id/edit(.:format)   lessons#edit
#      lesson GET    /lessons/:id(.:format)        lessons#show
#             PUT    /lessons/:id(.:format)        lessons#update
#             DELETE /lessons/:id(.:format)        lessons#destroy
end

# $ rake routes
#         lessons GET    /lessons(.:format)              lessons#index
#                 POST   /lessons(.:format)              lessons#create
#      new_lesson GET    /lessons/new(.:format)          lessons#new
#     edit_lesson GET    /lessons/:id/edit(.:format)     lessons#edit
#          lesson GET    /lessons/:id(.:format)          lessons#show
#                 PUT    /lessons/:id(.:format)          lessons#update
#                 DELETE /lessons/:id(.:format)          lessons#destroy
#     instructors POST   /instructors(.:format)          instructors#create
#  new_instructor GET    /instructors/new(.:format)      instructors#new
# edit_instructor GET    /instructors/:id/edit(.:format) instructors#edit
#      instructor GET    /instructors/:id(.:format)      instructors#show
#                 PUT    /instructors/:id(.:format)      instructors#update
#                 DELETE /instructors/:id(.:format)      instructors#destroy
#        sessions POST   /sessions(.:format)             sessions#create
#     new_session GET    /sessions/new(.:format)         sessions#new
#         courses GET    /courses(.:format)              courses#index
#                 POST   /courses(.:format)              courses#create
#      new_course GET    /courses/new(.:format)          courses#new
#     edit_course GET    /courses/:id/edit(.:format)     courses#edit
#          course GET    /courses/:id(.:format)          courses#show
#                 PUT    /courses/:id(.:format)          courses#update
#                 DELETE /courses/:id(.:format)          courses#destroy
#            root        /                               lessons#index
#                 POST   /lessons/:id/update(.:format)   lessons#update
#          logout GET    /logout(.:format)               sessions#destroy

app/models/instructor.rb
class Instructor < ActiveRecord::Base
  attr_accessible :username, :email, :password, :password_confirmation, :instructor_secret_code
  has_secure_password

  before_save :create_remember_token

  validates :username, presence: true, uniqueness: true
  validates :email, presence: true, uniqueness: true
  validates :password, presence: true, length: {minimum: 6}
  validates :password_confirmation, presence: true

  def create_remember_token
  	self.remember_token = SecureRandom.urlsafe_base64
  end

  has_many :course_instructors
  has_many :courses, through: :course_instructors

end

app/controllers/instructors_controller.rb
class InstructorsController < ApplicationController
skip_before_filter :authorize, only: [:new, :create]

def new
	@instructor = Instructor.new
end

def create
    @instructor = Instructor.create(params[:instructor])
    @instructor.update_attributes(instructor_secret_code: SecureRandom.urlsafe_base64)
	if @instructor.errors.empty?
		# InstructorMailer.welcome_email(@instructor).deliver
		sign_in(@instructor)
		redirect_to instructor_path(@instructor.instructor_secret_code) 
	else
		flash[:errors] = @instructor.errors.full_messages
		render :new
	end
end

def show
	@instructor = current_user
	@courses = @instructor.courses
	session[:instructor_id] = params[:id]
end

def edit
	@instructor = current_user
end

def update
	flash[:info] = "Your account has been updated"
	instructor = Instructor.find_by_instructor_secret_code(params[:id])
	instructor.update_attributes(username: params[:instructor][:username], email: params[:instructor][:email])
	redirect_to instructor_path(current_user.instructor_secret_code)
end

def destroy
	# No method yet for destroying Instructor.
	# Add this as a later feature.
end
end

app/helpers/instructors_helper.rb
module InstructorsHelper
end

app/views/instructors/edit.html.erb
<h1>Edit Account</h1>
<br>
<%= form_for @instructor, url: {action: "update"} do |f| %>
  <%= f.text_field :username, 					placeholder: "Username" %><br>
  <%= f.text_field :email, 						placeholder: "Email" %><br>
  <%= f.password_field :password, 				placeholder: "Password" %><br>
  <%= f.password_field :password_confirmation, 	placeholder: "Password Confirmation" %><br><br>
  <%= f.submit 'Update Instructor', class: 'btn btn-primary btn-lg' %>
<% end %>

app/views/instructors/new.html.erb
<h1>Join CourseBeat!</h1>
<br>
<%= form_for @instructor do |f| %>
  <%= f.text_field :username, 					placeholder: "Username" %><br>
  <%= f.text_field :email, 						placeholder: "Email" %><br>
  <%= f.password_field :password, 				placeholder: "Password" %><br>
  <%= f.password_field :password_confirmation, 	placeholder: "Password Confirmation" %><br><br>
  <%= f.submit 'Sign Up', :class => 'btn btn-success btn-lg' %>
  <%= link_to "Back to Home", lessons_path, class: 'btn btn-warning btn-lg' %>
<% end %>

app/views/instructors/show.html.erb
<h1>Courses for <%= @instructor.username %></h1><br>

<div class="buttonsBar">
	<div class="left"><a class="btn btn-success btn-lg" href="/courses/new" id="newLesson">New Course</a></div>
	<div class="right">
		<%= link_to "Edit Account", edit_instructor_path(params[:id]), class: "btn btn-info btn-lg" %>
		<%= link_to "Delete Account", "#", class: "btn btn-danger btn-lg" %>
	</div>
</div>
<br>
<% @courses.reverse.each do |course| %>
	<p>
   	<div class="left"><%= link_to course.course_name, course_path(course.secret_code) %></div>
   	<div class="right">
   		<%= link_to "View", course_path(course.secret_code), class: 'btn btn-primary' %>
   		<%= link_to "Edit", edit_course_path(course.secret_code), class: 'btn btn-info' %>
   		<%= link_to "Delete", course_path(course), :method => :delete, class: 'btn btn-danger' %>
   	</div></p>
<% end %>
<br>
<%= link_to "Back to Home", lessons_path, class: 'btn btn-warning' %>