config/routes.rb
Coursebeat::Application.routes.draw do

  resources :lessons, except: [:new, :create]
  resources :instructors, except: [:index]
  resources :sessions, only: [:new, :create]
  resources :courses do
  	resources :lessons, only: [:new, :create]
  end

  # get '/lessons/:secret_code', to: "lessons#show", as: "lesson_code"
  get '/courses/:secret_code', to: "courses#show", as: "course_code"
  # get '/instructors/:instructor_secret_code', to: "instructors#show", as: "instructor_code" 

  root to: "lessons#index"

  post "/lessons/:id/update", to: "lessons#update"

  post "/courses/:id/remove", to: "courses#remove_instructor", as: "remove_instructor"

  get '/logout' => "sessions#destroy"

  match '*path' => redirect('/')

# $ rake routes
#        root        /                             lessons#index
#             POST   /lessons/:id/update(.:format) lessons#update
#     lessons GET    /lessons(.:format)            lessons#index
#             POST   /lessons(.:format)            lessons#create
#  new_lesson GET    /lessons/new(.:format)        lessons#new
# edit_lesson GET    /lessons/:id/edit(.:format)   lessons#edit
#      lesson GET    /lessons/:id(.:format)        lessons#show
#             PUT    /lessons/:id(.:format)        lessons#update
#             DELETE /lessons/:id(.:format)        lessons#destroy
end

# $ rake routes
#         lessons GET    /lessons(.:format)              lessons#index
#                 POST   /lessons(.:format)              lessons#create
#      new_lesson GET    /lessons/new(.:format)          lessons#new
#     edit_lesson GET    /lessons/:id/edit(.:format)     lessons#edit
#          lesson GET    /lessons/:id(.:format)          lessons#show
#                 PUT    /lessons/:id(.:format)          lessons#update
#                 DELETE /lessons/:id(.:format)          lessons#destroy
#     instructors POST   /instructors(.:format)          instructors#create
#  new_instructor GET    /instructors/new(.:format)      instructors#new
# edit_instructor GET    /instructors/:id/edit(.:format) instructors#edit
#      instructor GET    /instructors/:id(.:format)      instructors#show
#                 PUT    /instructors/:id(.:format)      instructors#update
#                 DELETE /instructors/:id(.:format)      instructors#destroy
#        sessions POST   /sessions(.:format)             sessions#create
#     new_session GET    /sessions/new(.:format)         sessions#new
#         courses GET    /courses(.:format)              courses#index
#                 POST   /courses(.:format)              courses#create
#      new_course GET    /courses/new(.:format)          courses#new
#     edit_course GET    /courses/:id/edit(.:format)     courses#edit
#          course GET    /courses/:id(.:format)          courses#show
#                 PUT    /courses/:id(.:format)          courses#update
#                 DELETE /courses/:id(.:format)          courses#destroy
#            root        /                               lessons#index
#                 POST   /lessons/:id/update(.:format)   lessons#update
#          logout GET    /logout(.:format)               sessions#destroy

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
skip_before_filter :authorize, only: [:show]

def new
	@course = Course.new
end

def create
	# Check for presence of title and valid instructor
	if params[:course][:course_name] == ""
		redirect_to new_course_path, :flash => { :error => "Invalid course name"}
		return
	elsif params[:instructors] == nil
		redirect_to new_course_path, :flash => { :error => "Must include at least one valid instructor"}
		return
	end

	# Check that all instructors are valid
	params[:instructors].each do |num, username|
		instructor = Instructor.find_by_username(username)
		unless instructor
			redirect_to new_course_path, :flash => { :error => "Invalid instructor username"}
			return
		end
	end

	# Create course and join table entry for each instructor
	@course = Course.create(course_name: params[:course][:course_name], secret_code: SecureRandom.urlsafe_base64)
	params[:instructors].each do |num, username|
		instructor = Instructor.find_by_username(username)
		CourseInstructor.create(course_id: @course.id, instructor_id: instructor.id)
	end

	flash[:alert] = "Your course has been created."
	redirect_to instructor_path(current_user.instructor_secret_code)
end

def show
	@course = Course.find_by_secret_code(params[:id])
end

def edit
	@course = Course.find_by_secret_code(params[:id])
end

def update
	course = Course.find_by_secret_code(params[:id])
	course.update_attributes(course_name: params[:course][:course_name])
	if params[:instructors]
		params[:instructors].each do |key, name|
			instructor = Instructor.find_by_username(name)
			CourseInstructor.create(course_id: course.id, instructor_id: instructor.id)
		end
	end
	redirect_to course_path(params[:id])
end

def remove_instructor
	# This will be added later
	redirect_to edit_course_path(params[:id])
end

def destroy
	lesson = Course.destroy(params[:id])
	flash[:error] = lesson.course_name + " has been deleted"
	redirect_to instructor_path(session[:instructor_id])

end
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/views/courses/edit.html.erb
<h1>Edit Course Info</h1><br>
<%# binding.pry %>

<%= form_for @course, url: {action: "update"} do |c| %>
	<div class="title_bar">
  	<div class="left"><h2>Title: </h2> </div>
  	<div class="right"><%= c.text_field :course_name, placeholder: @course.course_name %></div> <br>
  	</div>
	<div class="left"><h2>Instructors:</h2></div>
	<div class="right"><input type="button" id="add_instructor" class="btn btn-primary btn-md" value="Add Instructor" onClick="addInstructor()"></div>
	<br>
	<% @course.instructors.each do |instructor| %>
		<p>
			<div class="left"><%= instructor.username %></div>
			<div class="right"><%= link_to "Remove", "#", :method => :delete, class: 'btn btn-danger' %></div>
		</p>
	<% end %>
  <div id="instructorHolder"></div><br>
  <%= c.submit "Update Course", class: 'btn btn-success btn-lg' %>
<% end %>

app/views/courses/new.html.erb
<h1>Create a Course</h1><br>

<%= form_for @course do |c| %>
  <%= c.text_field :course_name, placeholder: "Course name" %> 
  <input type="button" class="btn btn-primary btn-md" value="Add Instructor" onClick="addInstructor()"><br>
  <div id="instructorHolder"></div><br>
  <%= c.submit 'Create Course', class: 'btn btn-success btn-lg' %>
<% end %>

app/views/courses/show.html.erb
<div class="top">
	<% if current_user %> 
		<h1>Lessons for <%= @course.course_name %></h1>
	<% else %>
		<h1>Lessons for <%= @course.course_name %></h1>
	<% end %>
</div>

<div class="info-bar">
	<div class="left">
	<%= link_to "New Lesson", new_course_lesson_path(@course.secret_code), class: "btn btn-success btn-lg", id: "newLessonButton" %>
	</div>
	<div class="right">
		<h2>Instructors:</h2>
		<% @course.instructors.each do |instructor| %>
			<p><%= instructor.username %></p>
		<% end %>
	</div>
</div>

<% @course.lessons.reverse.each do |entry| %>
	<p>
   	<div class="left"><%= link_to entry.title, lesson_path(entry.secret_code) %></div>
   	<div class="right">
   		<%= link_to "Edit", edit_lesson_path(entry), class: 'btn btn-primary' %>
   		<%= link_to "Delete", lesson_path(entry), :method => :delete, class: 'btn btn-danger' %>
   	</div>
   	</p>
<% end %>
<br>

<% if current_user %>
<%= link_to "Back to Course List", instructor_path(current_user.instructor_secret_code), class: 'btn btn-warning' %>
<% end %>