config/routes.rb
Coursebeat::Application.routes.draw do

  resources :lessons, except: [:new, :create]
  resources :instructors, except: [:index]
  resources :sessions, only: [:new, :create]
  resources :courses do
  	resources :lessons, only: [:new, :create]
  end

  # get '/lessons/:secret_code', to: "lessons#show", as: "lesson_code"
  get '/courses/:secret_code', to: "courses#show", as: "course_code"
  # get '/instructors/:instructor_secret_code', to: "instructors#show", as: "instructor_code" 

  root to: "lessons#index"

  post "/lessons/:id/update", to: "lessons#update"

  post "/courses/:id/remove", to: "courses#remove_instructor", as: "remove_instructor"

  get '/logout' => "sessions#destroy"

  match '*path' => redirect('/')

# $ rake routes
#        root        /                             lessons#index
#             POST   /lessons/:id/update(.:format) lessons#update
#     lessons GET    /lessons(.:format)            lessons#index
#             POST   /lessons(.:format)            lessons#create
#  new_lesson GET    /lessons/new(.:format)        lessons#new
# edit_lesson GET    /lessons/:id/edit(.:format)   lessons#edit
#      lesson GET    /lessons/:id(.:format)        lessons#show
#             PUT    /lessons/:id(.:format)        lessons#update
#             DELETE /lessons/:id(.:format)        lessons#destroy
end

# $ rake routes
#         lessons GET    /lessons(.:format)              lessons#index
#                 POST   /lessons(.:format)              lessons#create
#      new_lesson GET    /lessons/new(.:format)          lessons#new
#     edit_lesson GET    /lessons/:id/edit(.:format)     lessons#edit
#          lesson GET    /lessons/:id(.:format)          lessons#show
#                 PUT    /lessons/:id(.:format)          lessons#update
#                 DELETE /lessons/:id(.:format)          lessons#destroy
#     instructors POST   /instructors(.:format)          instructors#create
#  new_instructor GET    /instructors/new(.:format)      instructors#new
# edit_instructor GET    /instructors/:id/edit(.:format) instructors#edit
#      instructor GET    /instructors/:id(.:format)      instructors#show
#                 PUT    /instructors/:id(.:format)      instructors#update
#                 DELETE /instructors/:id(.:format)      instructors#destroy
#        sessions POST   /sessions(.:format)             sessions#create
#     new_session GET    /sessions/new(.:format)         sessions#new
#         courses GET    /courses(.:format)              courses#index
#                 POST   /courses(.:format)              courses#create
#      new_course GET    /courses/new(.:format)          courses#new
#     edit_course GET    /courses/:id/edit(.:format)     courses#edit
#          course GET    /courses/:id(.:format)          courses#show
#                 PUT    /courses/:id(.:format)          courses#update
#                 DELETE /courses/:id(.:format)          courses#destroy
#            root        /                               lessons#index
#                 POST   /lessons/:id/update(.:format)   lessons#update
#          logout GET    /logout(.:format)               sessions#destroy

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Coursebeat</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<nav class="navbar navbar-default navbar-static-top navbar-inverse" role="navigation">
	<a class="navbar-brand" href="/lessons"><span class="glyphicon glyphicon-book"></span> CourseBeat</a>
	<ul class="nav navbar-nav navbar-right">
		
			<% if current_user %>
				<li><%= link_to "Welcome, " + current_user.username, instructor_path(current_user.instructor_secret_code) %></li>
				<li><%= link_to "Logout", logout_path, method: "get" %></li>
			<% else %>
				<li><%= link_to "Sign Up", new_instructor_path %></li>
				<li><%= link_to "Login", new_session_path, method: "get" %></li>
			<% end %>
		
	</ul>
</nav>



<div class="jumbotron">
<% if flash[:alert] %>
	<div class="alert alert-success"><%= flash[:alert] if flash[:alert] %></div>
<% end %>
<% if flash[:error] %>
<div class="alert alert-danger"><%= flash[:error] if flash[:error] %></div>
<% end %>
<% if flash[:info] %>
<div class="alert alert-info"><%= flash[:info] if flash[:info] %></div>
<% end %>

<%= yield %>
</div>


<!-- <%= params.inspect %> -->
</body>
</html>